### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by eodonnellCLIR** [waynegraham/ija-omeka-s#19]
![Screen Shot 2023-01-06 at 10 49 36 AM](https://user-images.githubusercontent.com/122109967/211049104-284e0863-3a3a-445f-ab9f-8b9ba5b46759.png)

“2003 Memorandum of Agreement” and "Report" links on https://omeka.ijarchive.org/s/iraqi-jewish-archive/page/recovery-artifacts#

**Comment by waynegraham** [comment]
Links have been updated.
