### ISSUE TITLE
Advanced search: full-text search doesn't work

### ISSUE THREAD

**Issue by alucko** [waynegraham/ija-omeka-s#20]
In Advanced Search, regular full-text search isn't working. The system defaults to whatever is in the Search by value box. Example: I put "sheep" in the full-text search box and left the Search by value box alone (the default setting seems to be "[Any Property]+[is exactly]"). It returned 3,604 results. If I put "sheep" into the search by value box and change it to "contains" then I get 3 results (which is presumably correct, they all contain "sheep" in their description somewhere).

**Comment by waynegraham** [comment]
Query string (e.g. `sheep`) is not being passed to the item search. Need to figure out why the `fulltext_search=sheep` parameter is not being passed as expected. 

Full URL should be: https://omeka.ijarchive.org/s/iraqi-jewish-archive/item/search?sort_by=created&sort_order=desc&page=1&fulltext_search=sheep
