### ISSUE TITLE
Text justified all the way to left w/ no margin on https://ijarchive.org/search

### ISSUE THREAD

**Issue by jreeveseyre** [waynegraham/ija-omeka-s#21]
See screenshot. On my work mac, using firefox. 
<img width="1211" alt="Screen Shot 2023-01-09 at 9 26 36 AM" src="https://user-images.githubusercontent.com/50340542/211331054-478c9dd3-acaf-41ff-bcb1-ee7321b6ef3a.png">

**Comment by waynegraham** [comment]
I believe this screenshot is from the "old" site. This text has been migrated to https://omeka.ijarchive.org/s/iraqi-jewish-archive/page/about which should have proper breakpoints.
